# =====================================================
# PROD Profile
# =====================================================

# MySQL — all from env vars, no fallbacks
spring.datasource.url=jdbc:postgresql://dpg-d7bfs1ruibrs739niiig-a:5432/collabrium_db
spring.datasource.username=collabrium_db_user
spring.datasource.password=bBE8nkJsCch2haCAEf2sc5mll6bGaWEs

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
