# =====================================================
# PROD Profile
# =====================================================

# MySQL — all from env vars, no fallbacks
spring.datasource.url=jdbc:mysql://sql100.infinityfree.com:3306/if0_41607106_collabrium_db
spring.datasource.username=if0_41607106
spring.datasource.password=MOk3468OHZAKI

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
