# =====================================================
# BASE Configuration — secrets always via env vars
# =====================================================
spring.profiles.active=dev

# JWT Configuration
jwt.secret=${JWT_SECRET:collabrium-super-secret-key-must-be-at-least-256-bits-long-for-hs256}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}


spring.datasource.url=jdbc:postgresql://dpg-d7bfs1ruibrs739niiig-a:5432/collabrium_db
spring.datasource.username=collabrium_db_user
spring.datasource.password=bBE8nkJsCch2haCAEf2sc5mll6bGaWEs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
